# Generated by Django 2.2.2 on 2019-06-26 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_acct',
            name='id_acct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acct.Type_acct'),
        ),
        migrations.AddField(
            model_name='user_acct',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_acct',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
